### ISSUE TITLE
Error in .run() function while running the DES code.

### ISSUE THREAD

**Issue by ninjha252** [sequence-toolbox/SeQUeNCe#162]
Hello, I've been trying to run the DES code given on the instruction page after installing SeQUeNCe, and I'm facing a type error which is pointing me to the documentation files of timeline.py and process.py The error in coming when I'm trying to do tl.run() and it's giving a type error of "bool" being called. The error is pointed to the above two mentioned files. I've also run the gui.py script and its working perfectly. I do not think its an installation error. Kindly give me pointers to how I can solve this. I've attached a picture of the error below, where the trial.txt file contains the DES code from the SeQUeNCe documentation website. 

![error_message (1)](https://github.com/sequence-toolbox/SeQUeNCe/assets/73876816/843538b0-fe68-4aaf-b52b-72fecbbef892)

**Comment by JoaquinChung** [comment]
Hi Nitin, what is in your `trial.txt` file? If that's your simulation script, try changing the extension to `.py` and let us know how it goes.

**Comment by ninjha252** [comment]
Hello,

Thank you for the reply! So the problem was in using .open() instead of
.opening()

I used .open() as it was on the documentation file, however it was showing
the type error of bool. I realised it quite late and changed it and it
started working.

Than you!
Sincerely,
Nitin Jha.
