### ISSUE TITLE
Error in Tutorial 2 Docs

### ISSUE THREAD

**Issue by DMcDe** [sequence-toolbox/SeQUeNCe#165]
Following the code provided in tutorial 2 exactly (to put a qubit into a superposition and then measure it on a ReceiverNode) results in the qubit being detected 100% of the time, no matter what state you put it in. 

Modifying the code as follows resolved the issue for me. I changed:

```
def receive_qubit(self, src, qubit): 
        self.components[self.first_component_name].get()
```
to
```
def receive_qubit(self, src, qubit):
        self.components[self.first_component_name].get(qubit)
```

I believe the docs should be updated to reflect this (although I am new to SeQUeNCe, so I may be doing something incorrectly).

**Comment by caitaozhan** [comment]
Hi DMcDe,

The error in the tutorial is now fixed. This issue will be closed soon.

Thanks,
Caitao
