### ISSUE TITLE
Convert photons/measurement devices to use new quantum manager

### ISSUE THREAD

**Issue by Alex-Kolar** [sequence-toolbox/SeQUeNCe#27]
- [ ] update photon class
- [ ] update encodings
- [ ] update QSD, beamsplitter, interferometer classes

**Comment by xwu64** [comment]
should I close this issue?

**Comment by Alex-Kolar** [comment]
I think we discussed this and decided to leave the photons as-is, while using the quantum manager only for memories. As such the issue can be closed.
