### ISSUE TITLE
Add density matrix support

### ISSUE THREAD

**Issue by Alex-Kolar** [sequence-toolbox/SeQUeNCe#30]
- [x] create base quantum manager class
- [x] create new quantum manager type
- [x] create new class `DensityState`
- [x] update measurement functions
- [x] add unit tests

**Comment by xwu64** [comment]
1. Could we move line 106-135 and line 248-279 of quantum_manager.py to the class `QuantumManager` as a new function? This function should return the unitary matrix with swapping circuit. I think it could reduce the duplicated code in the file. In the future, if we need to change the logic of this part, we don't need to change code in both classes. 

2. Could you create unit test for `QuantumManagerDensity.run_circuit`? We want to ensure the circuit run properly with pure or mixed state.

**Comment by Alex-Kolar** [comment]
1. Yes, I can move some code to the parent method. The swapping of qubits will need to remain in each child class, but the combining of the quantum states and the circuit matrix definition are general.

2. Yes, I'll add unit tests.

**Comment by xwu64** [comment]
1. Why the swapping of qubits need separate code? I think the swapping circuit will be same regardless the formalism of quantum state. We can multiply unitary matrix of input circuit and swapping circuit to generate real circuit, which could be done by a function in the parent class. Child class will multiply quantum state with the generated circuit based on the formalism of quantum state.

**Comment by Alex-Kolar** [comment]
Ah, I understand. In the current implementation, the swapping is performed as a separate circuit. You should be right in that it can simply be multiplied into to the regular circuit matrix. I'll do that.

**Comment by xwu64** [comment]
We should not put the logic in the `run_circuit` function of parent class because it make the type of return different from child class. We can create a new function to place these logic. Child could call the new function to generate matrix. 

I also notice the logic of generating swapping circuit appears 3 locations. Maybe we can also create a function in the parent class to generate desired swapping circuit.

**Comment by Alex-Kolar** [comment]
This has been added, with the functionality moved to '_prepare_circuit' and the swapping operations generated by '_swap_qubits'
