### ISSUE TITLE
What is a Memory's raw fidelity?

### ISSUE THREAD

**Issue by LesterKim** [sequence-toolbox/SeQUeNCe#36]
What does [raw_fidelity](https://github.com/sequence-toolbox/SeQUeNCe/blob/master/src/components/memory.py#L137) mean for a `Memory`?

Traditionally, [the fidelity is a measure of closeness between two quantum states](https://en.wikipedia.org/wiki/Fidelity_of_quantum_states). However, it is unclear what `raw_fidelity` means in this context.

**Comment by xwu64** [comment]
First, I'm sorry for confusion. The reason of using `raw_fidelity` in the `Memory` class is to mimic errors during the generation of entanglement. Although a float number is too simple to represent errors in the entanglement completely, this number is sufficient to simulate some cases in the quantum networks (like representing the quality of entanglement after distillation or swapping). 

We also implemented KetState and DensityMatrix in the quantum manager in the RnD branch, which may represent quantum states more accurately. However, the exact quantum state should be hidden from the control logic. The `raw_fidelity` and `fidelity` of `Memory` could be attributes that are known by the control logic to represent the quality of entanglement.

**Comment by LesterKim** [comment]
Thank you for responding. If Alice's entangled `Memory`'s fidelity as part of the first Bell state (i.e. phi plus) is `0.9`, then she has a 90% chance of having the same measurement value (in the Z basis) as Bob's (i.e. her measurement coincides with his)?

**Comment by xwu64** [comment]
> Thank you for responding. If Alice's entangled `Memory`'s fidelity as part of the first Bell state (i.e. phi plus) is `0.9`, then she has a 90% chance of having the same measurement value (in the Z basis) as Bob's (i.e. her measurement coincides with his)?

It means it has 90% chance to get the desired bell state and 3.33% chance to get the rest of three bell state respectively.

**Comment by LesterKim** [comment]
In SeQUeNCe, when Alice and Bob share an entangled pair of memory qubits, the pair can only be in one of the four Bell states (i.e. phi/psi plus/minus)?

**Comment by xwu64** [comment]
> In SeQUeNCe, when Alice and Bob share an entangled pair of memory qubits, the pair can only be in one of the four Bell states (i.e. phi/psi plus/minus)?

Current error model is designed like that, but we also welcome people to design their own error model.

**Comment by LesterKim** [comment]
> > In SeQUeNCe, when Alice and Bob share an entangled pair of memory qubits, the pair can only be in one of the four Bell states (i.e. phi/psi plus/minus)?
> 
> Current error model is designed like that, but we also welcome people to design their own error model.

Got it. Thank you.
