### ISSUE TITLE
Edit chapter 2 of tutorial for repeated operation

### ISSUE THREAD

**Issue by LesterKim** [sequence-toolbox/SeQUeNCe#37]
- [x] Replace second `event1` in [the code in Step 5](https://github.com/sequence-toolbox/SeQUeNCe/blob/master/docs/source/tutorial/chapter2/hardware.md) with `event2`
- [x] Replace Step 7 with Step 6
- [x] Replace second to last sentence with `In the output, we see that the PING message is received on node 2 first, followed by a PONG message received on node 1.`

**Comment by xwu64** [comment]
Thanks for your comments!

BTW, please feel free to clone our repository and create merge request for correcting issues. It's our pleasure to leave your contribution on our project.
